version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Unit test
          command: |
            npm install
            npm run test
          environment:
            JEST_OUTPUT: "reports/jest/js-test-results.xml"
      - store_artifacts:
          path: /coverage
          destination: artifact-file
